rophako:
  site:
    debug: false
    site_name: kirsle.net
    site_root: /home/kirsle/git/kirsle.net/www
  security:
    force_ssl: true
    secret_key: something random
    use_forwarded_for: true
  db:
    db_root: /home/kirsle/git/kirsle.net/db
    redis_db: 1
  mail:
    sender: Kirsle.net <no-reply@kirsle.net>
  blog:
    title: Kirsle.net Blog
    link: https://www.kirsle.net/
    description: Kirsle's web blog.
    image_title: Kirsle.net Blog
    image_url: https://www.kirsle.net/static/avatars/casey.png
    image_description: Kirsle.net
  photo:
    root_private: /home/kirsle/www/static/photos
  custom:
    - kirsle_legacy
