rophako:
  site:
    debug: false
    site_name: kirsle.net
    site_root: ../www
  security:
    secret_key: something random
    use_forwarded_for: true
  db:
    db_root: db
    redis_prefix: "kirsle.net:"
  mail:
    sender: Kirsle.net <no-reply@kirsle.net>
  blog:
    title: Kirsle.net Blog
    link: https://www.kirsle.net/
    description: Kirsle's web blog.
    image_title: Kirsle.net Blog
    image_url: https://www.kirsle.net/static/avatars/casey.png
    image_description: Kirsle.net
  photo:
    root_private: ../www/static/photos
  custom:
    - kirsle_legacy
